# Netlify Dev
# https://cli.netlify.com/netlify-dev/#netlifytoml-dev-block

# 제품 모드
[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"

# 개발 모드
[dev]
  framework = "#custom"
  command = "yarn dev:webpack"
  targetPort = 3000
  port = 8080
  publish = "dist"
  autoLaunch = false